package touchque

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// Cross-language SDK contract fixtures, generated by the backend from its own
// utils/canonicalSignature.js + utils/webhookCanonical.js. Asserted here and in
// the node/php/python suites so every SDK signs and canonicalises identically to
// the server (would have caught the 2026-08 webhook + GET-query regressions).

func readFixture(t *testing.T, name string, out interface{}) {
	t.Helper()
	p := filepath.Join("..", "fixtures", name)
	b, err := os.ReadFile(p)
	if err != nil {
		t.Fatalf("read %s: %v", p, err)
	}
	if err := json.Unmarshal(b, out); err != nil {
		t.Fatalf("unmarshal %s: %v", p, err)
	}
}

func TestSignatureVectors(t *testing.T) {
	var fx struct {
		Secret  string `json:"secret"`
		Vectors []struct {
			Description       string            `json:"description"`
			Method            string            `json:"method"`
			SignedPath        string            `json:"signed_path"`
			Body              string            `json:"body"`
			BasePath          string            `json:"base_path"`
			Query             map[string]string `json:"query"`
			Timestamp         string            `json:"timestamp"`
			Nonce             string            `json:"nonce"`
			ExpectedSignature string            `json:"expected_signature"`
		} `json:"vectors"`
	}
	readFixture(t, "signature-vectors.json", &fx)
	if len(fx.Vectors) == 0 {
		t.Fatal("no signature vectors")
	}

	h := newHTTPClient(&Config{APIKey: "tq_x", APISecret: fx.Secret})
	for _, v := range fx.Vectors {
		t.Run(v.Description, func(t *testing.T) {
			got := h.signRequest(v.Method, v.SignedPath, []byte(v.Body), v.Timestamp, v.Nonce)
			if got != v.ExpectedSignature {
				t.Fatalf("signature mismatch\n got: %s\nwant: %s", got, v.ExpectedSignature)
			}
		})
	}
}

func TestWebhookVectors(t *testing.T) {
	var fx struct {
		Secret  string `json:"secret"`
		Vectors []struct {
			Description       string          `json:"description"`
			Payload           json.RawMessage `json:"payload"`
			ExpectedCanonical string          `json:"expected_canonical"`
			ExpectedSignature string          `json:"expected_signature"`
			DeliveredBody     string          `json:"delivered_body"`
		} `json:"vectors"`
	}
	readFixture(t, "webhook-vectors.json", &fx)
	if len(fx.Vectors) == 0 {
		t.Fatal("no webhook vectors")
	}

	w := newWebhookResource(&Config{APIKey: "tq_x", APISecret: fx.Secret})
	for _, v := range fx.Vectors {
		t.Run(v.Description, func(t *testing.T) {
			canon, err := canonicalize(v.Payload)
			if err != nil {
				t.Fatalf("canonicalize: %v", err)
			}
			if canon != v.ExpectedCanonical {
				t.Fatalf("canonical mismatch\n got: %s\nwant: %s", canon, v.ExpectedCanonical)
			}
			mac := hmac.New(sha256.New, []byte(fx.Secret))
			mac.Write([]byte(canon))
			if hex.EncodeToString(mac.Sum(nil)) != v.ExpectedSignature {
				t.Fatal("webhook signature mismatch")
			}
			// Verify accepts the delivered body. Fixtures carry a fixed past
			// (or no) timestamp, so the freshness check is switched off here.
			if _, verr := w.Verify(v.DeliveredBody, "", 0); verr != nil {
				t.Fatalf("Verify rejected a valid fixture: %v", verr)
			}
		})
	}
}
